# Generated by Django 5.0.3 on 2024-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
